import {
  CanvasPreset,
  KashmiriCharInfo,
  KashurTemplate,
  KeyboardKey,
  TextStyleProperties
} from '../types';

export const DEFAULT_TEXT_STYLE: TextStyleProperties = {
  fontFamily: 'Noto Nastaliq Urdu',
  fontSize: 12,
  bold: false,
  italic: false,
  underline: false,
  color: '#1c1917', // stone-900
  align: 'right',
  verticalAlign: 'top',
  lineHeight: 2.2,
  letterSpacing: 0,
  direction: 'rtl',
  opacity: 1,
};

// Canvas Presets for Design Studio
export const CANVAS_PRESETS: CanvasPreset[] = [
  {
    id: '1:1',
    name: 'Square',
    nameKashmiri: 'مورَبَع (1:1)',
    width: 1080,
    height: 1080,
    aspectRatio: '1/1',
    icon: 'Square',
    description: 'Instagram Posts, WhatsApp Profile, Poetry Cards',
  },
  {
    id: '4:5',
    name: 'Portrait Feed',
    nameKashmiri: 'عمودی (4:5)',
    width: 1080,
    height: 1350,
    aspectRatio: '4/5',
    icon: 'RectangleVertical',
    description: 'Instagram Feed, Facebook Portrait Cards',
  },
  {
    id: '9:16',
    name: 'Story & Status',
    nameKashmiri: 'سٹوری / سٹیٹس (9:16)',
    width: 1080,
    height: 1920,
    aspectRatio: '9/16',
    icon: 'Smartphone',
    description: 'WhatsApp Status, Instagram Story, Reels cover',
  },
  {
    id: '16:9',
    name: 'Landscape Banner',
    nameKashmiri: 'افقی بینر (16:9)',
    width: 1920,
    height: 1080,
    aspectRatio: '16/9',
    icon: 'Monitor',
    description: 'YouTube Thumbnail, Website Header, Banner',
  },
  {
    id: 'a4',
    name: 'A4 Notice / Poster',
    nameKashmiri: 'اے فور پوسٹر',
    width: 1240,
    height: 1754,
    aspectRatio: '1/1.414',
    icon: 'FileText',
    description: 'School Announcements, Event Notices, Printables',
  },
];

// Complete Kashmiri Character Database
export const KASHMIRI_CHARACTERS_DB: KashmiriCharInfo[] = [
  // Kashmiri Specific Vowels & Letters
  {
    char: 'ٲ',
    name: 'Kashmiri Alif with Madda',
    nameKashmiri: 'ٲلِف مَدٕ',
    unicodeHex: 'U+0672',
    category: 'vowel',
    sound: 'Open-mid back unrounded vowel [ʌ] / [ɔ]',
    exampleWord: 'ٲسۍ',
    exampleMeaning: 'We / Us (Aesy)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ٳ',
    name: 'Kashmiri Alif with Hamza below',
    nameKashmiri: 'ٳلِف تَلی ہَمزَہ',
    unicodeHex: 'U+0673',
    category: 'vowel',
    sound: 'Close central unrounded vowel [ɨ] / [ɯ]',
    exampleWord: 'ٳنٛسان',
    exampleMeaning: 'Human (Insaan variant)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ۄ',
    name: 'Kashmiri Waw with Ring',
    nameKashmiri: 'حَلقہٕ دار واو',
    unicodeHex: 'U+06C4',
    category: 'vowel',
    sound: 'Open-mid back rounded vowel [ɔ]',
    exampleWord: 'ۄپھُن',
    exampleMeaning: 'To fly (Wophun)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ۄٚ',
    name: 'Kashmiri Waw with Inverted V',
    nameKashmiri: 'واو پؠٹھ اۄلٹا وی',
    unicodeHex: 'U+06C4 + U+065A',
    category: 'vowel',
    sound: 'Short rounded vowel [ŏ]',
    exampleWord: 'کۄٚل',
    exampleMeaning: 'Stream / Canal (Kol)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ۆ',
    name: 'Kashmiri Waw with V / Caron',
    nameKashmiri: 'واو پؠٹھ وی',
    unicodeHex: 'U+06C6',
    category: 'vowel',
    sound: 'Close-mid back rounded vowel [o]',
    exampleWord: 'ۆل',
    exampleMeaning: 'Nest (Ol)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ؠ',
    name: 'Kashmiri Yeh (Tshae / Tse)',
    nameKashmiri: 'کٲشُر یے (چھٔ)',
    unicodeHex: 'U+0620',
    category: 'letter',
    sound: 'Palatalized semi-vowel / Kashmiri distinct sound [ʲ] / [j]',
    exampleWord: 'دٔلیٖل',
    exampleMeaning: 'Story / Tale (Daleel)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ےٚ',
    name: 'Kashmiri Bari Ye with Inverted V',
    nameKashmiri: 'بٔڑی یے پؠٹھ اۄلٹا وی',
    unicodeHex: 'U+06D2 + U+065A',
    category: 'vowel',
    sound: 'Short front vowel [ĕ]',
    exampleWord: 'مےٚ',
    exampleMeaning: 'Me / To me (Me)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ێ',
    name: 'Kashmiri Yeh with Inverted V above',
    nameKashmiri: 'یے پؠٹھ وی',
    unicodeHex: 'U+06CE',
    category: 'letter',
    sound: 'Kashmiri vowel Yeh',
    exampleWord: 'سێند',
    exampleMeaning: 'River / Indus variant',
    isKashmiriSpecific: true,
  },
  // Diacritics
  {
    char: 'َ',
    name: 'Zabar (Fatha)',
    nameKashmiri: 'زَبَر (فَتحَہ)',
    unicodeHex: 'U+064E',
    category: 'diacritic',
    sound: 'Short "a" vowel sound [a]',
    exampleWord: 'کَر',
    exampleMeaning: 'Do (Kar)',
  },
  {
    char: 'ِ',
    name: 'Zer (Kasra)',
    nameKashmiri: 'زیر (کَسرَہ)',
    unicodeHex: 'U+0650',
    category: 'diacritic',
    sound: 'Short "i" vowel sound [i]',
    exampleWord: 'دِل',
    exampleMeaning: 'Heart (Dil)',
  },
  {
    char: 'ُ',
    name: 'Pesh (Damma)',
    nameKashmiri: 'پیش (ضَمَہ)',
    unicodeHex: 'U+064F',
    category: 'diacritic',
    sound: 'Short "u" vowel sound [u]',
    exampleWord: 'پُل',
    exampleMeaning: 'Bridge (Pul)',
  },
  {
    char: 'ْ',
    name: 'Jazm / Sukun',
    nameKashmiri: 'جَزم / سُکون',
    unicodeHex: 'U+0652',
    category: 'diacritic',
    sound: 'Vowelless marker',
    exampleWord: 'سَردْ',
    exampleMeaning: 'Cold',
  },
  {
    char: 'ّ',
    name: 'Tashdeed (Shaddah)',
    nameKashmiri: 'تَشدِید',
    unicodeHex: 'U+0651',
    category: 'diacritic',
    sound: 'Consonant gemination (doubling)',
    exampleWord: 'اَچّھ',
    exampleMeaning: 'Eye (Achh)',
  },
  {
    char: '٘',
    name: 'Kashmiri Small High V',
    nameKashmiri: 'چھۄٹ وی اِعراب',
    unicodeHex: 'U+0658',
    category: 'combining',
    sound: 'Kashmiri specific vowel modifier',
    exampleWord: 'گ٘رٛانٛد',
    exampleMeaning: 'Counting (Grand)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ٚ',
    name: 'Kashmiri Small High Inverted V',
    nameKashmiri: 'اۄلٹٕ وی اِعراب',
    unicodeHex: 'U+065A',
    category: 'combining',
    sound: 'Kashmiri short vowel diacritic',
    exampleWord: 'تٚر',
    exampleMeaning: 'Float / Cross',
    isKashmiriSpecific: true,
  },
  {
    char: 'ٔ',
    name: 'Hamza Above',
    nameKashmiri: 'ہَمزَہ پؠٹھ',
    unicodeHex: 'U+0654',
    category: 'combining',
    sound: 'Kashmiri short high vowel / vocalic break',
    exampleWord: 'پٔز',
    exampleMeaning: 'Truth / Real (Paez)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ٕ',
    name: 'Hamza Below',
    nameKashmiri: 'ہَمزَہ تَل',
    unicodeHex: 'U+0655',
    category: 'combining',
    sound: 'Kashmiri central vowel [ɨ]',
    exampleWord: 'سٕریٖنَگَر',
    exampleMeaning: 'Srinagar (city of Kashmir)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ٖ',
    name: 'Khadi Zer (Subscript Alef)',
    nameKashmiri: 'کھٔڑی زیر',
    unicodeHex: 'U+0656',
    category: 'diacritic',
    sound: 'Long "ee" vowel',
    exampleWord: 'بِہٖ',
    exampleMeaning: 'With Him',
  },
  {
    char: 'ٗ',
    name: 'Ulta Pesh (Inverted Damma)',
    nameKashmiri: 'اۄلٹٕ پیش',
    unicodeHex: 'U+0657',
    category: 'diacritic',
    sound: 'Long "oo" sound',
    exampleWord: 'لَہٗ',
    exampleMeaning: 'For Him',
  },
  {
    char: 'ٰ',
    name: 'Khada Zabar (Superscript Alef)',
    nameKashmiri: 'کھڑا زَبَر',
    unicodeHex: 'U+0670',
    category: 'diacritic',
    sound: 'Long "aa" vowel',
    exampleWord: 'عیسیٰ',
    exampleMeaning: 'Isa (Jesus)',
  },
  {
    char: 'ں',
    name: 'Noon Ghunna',
    nameKashmiri: 'نُون غُنَہ',
    unicodeHex: 'U+06BA',
    category: 'letter',
    sound: 'Nasalization',
    exampleWord: 'ماں',
    exampleMeaning: 'Mother',
  },
  {
    char: 'ژ',
    name: 'Tcheh / Jeem with 3 dots',
    nameKashmiri: 'ژے (ژ)',
    unicodeHex: 'U+0698',
    category: 'letter',
    sound: 'Voiceless alveolar affricate [ts]',
    exampleWord: 'ژۄنٛگ',
    exampleMeaning: 'Lamp (Tsong)',
    isKashmiriSpecific: true,
  },
  {
    char: 'چ',
    name: 'Che',
    nameKashmiri: 'چے',
    unicodeHex: 'U+0686',
    category: 'letter',
    sound: '[tʃ]',
    exampleWord: 'چائے',
    exampleMeaning: 'Tea (Chai)',
  },
  {
    char: 'پ',
    name: 'Pe',
    nameKashmiri: 'پے',
    unicodeHex: 'U+067E',
    category: 'letter',
    sound: '[p]',
    exampleWord: 'پَنُن',
    exampleMeaning: 'Own (Panun)',
  },
  {
    char: 'ٹ',
    name: 'Tte',
    nameKashmiri: 'ٹے',
    unicodeHex: 'U+0679',
    category: 'letter',
    sound: 'Retroflex [ʈ]',
    exampleWord: 'ٹاٹھیٖ',
    exampleMeaning: 'Dear (Taathi)',
  },
  {
    char: 'ڈ',
    name: 'Ddal',
    nameKashmiri: 'ڈال',
    unicodeHex: 'U+0688',
    category: 'letter',
    sound: 'Retroflex [ɖ]',
    exampleWord: 'ڈَل',
    exampleMeaning: 'Dal Lake',
  },
  {
    char: 'ڑ',
    name: 'Rre',
    nameKashmiri: 'ڑے',
    unicodeHex: 'U+0691',
    category: 'letter',
    sound: 'Retroflex flap [ɽ]',
    exampleWord: 'گٲڑِ',
    exampleMeaning: 'Fish / Car (Gaadi)',
  },
  {
    char: 'ھ',
    name: 'Dochashmi He',
    nameKashmiri: 'دو چَشمی ہے',
    unicodeHex: 'U+06BE',
    category: 'letter',
    sound: 'Aspiration marker (bh, ph, th, etc.)',
    exampleWord: 'گھَر',
    exampleMeaning: 'Home (Ghar)',
  },
  {
    char: 'ہ',
    name: 'Goal He',
    nameKashmiri: 'گول ہے',
    unicodeHex: 'U+06C1',
    category: 'letter',
    sound: '[h]',
    exampleWord: 'ہَوا',
    exampleMeaning: 'Air / Breeze',
  },
  {
    char: 'ے',
    name: 'Bari Ye',
    nameKashmiri: 'بٔڑی یے',
    unicodeHex: 'U+06D2',
    category: 'letter',
    sound: 'Long "e" vowel [eː]',
    exampleWord: 'سارِوٕے',
    exampleMeaning: 'All (Saarwi)',
  },
];

// Dedicated Keyboard Layouts - Clean, non-duplicated Kashmiri & Perso-Arabic layout
export const KASHMIRI_KEYBOARD_LAYOUTS = {
  // Main letters (Layout 1 - حروف) - Clean, zero-duplication standard & Kashmiri letters prioritized
  main: [
    // Row 1: Kashmiri vowels & top special consonants
    [
      { char: 'ٲ', isKashmiriSpecial: true, longPress: ['ٳ', 'آ', 'أ', 'إ'] },
      { char: 'ۄ', isKashmiriSpecial: true, longPress: ['ۄٚ', 'ۆ', 'و', 'ؤ'] },
      { char: 'ؠ', isKashmiriSpecial: true, longPress: ['ی', 'ے', 'ےٚ', 'ێ'] },
      { char: 'ژ', isKashmiriSpecial: true },
      { char: 'چ' },
      { char: 'پ' },
      { char: 'ٹ', longPress: ['ط'] },
      { char: 'ڈ' },
      { char: 'ڑ', longPress: ['ر'] },
      { char: 'ں', longPress: ['ن'] },
      { char: 'ھ', longPress: ['پھ', 'تھ', 'ٹھ', 'چھ', 'جھ', 'بھ', 'دھ', 'ڈھ', 'کھ', 'گھ'] },
    ],
    // Row 2: Home row core consonants
    [
      { char: 'ش' },
      { char: 'س', longPress: ['ص', 'ث'] },
      { char: 'ی', longPress: ['ے', 'ےٚ', 'ێ', 'ؠ', 'ئ', 'یٛ'] },
      { char: 'ب' },
      { char: 'ل', longPress: ['لا', 'لٲ'] },
      { char: 'ا', longPress: ['آ', 'ٲ', 'ٳ', 'أ', 'إ', 'ٱ'] },
      { char: 'ت', longPress: ['ۃ'] },
      { char: 'ن', longPress: ['ݨ', 'ں'] },
      { char: 'م' },
      { char: 'ک' },
      { char: 'گ' },
    ],
    // Row 3: Bottom row letters
    [
      { char: 'ف', longPress: ['ڤ', 'ق'] },
      { char: 'غ', longPress: ['ع'] },
      { char: 'ح', longPress: ['خ'] },
      { char: 'ج' },
      { char: 'د', longPress: ['ذ'] },
      { char: 'ر', longPress: ['ڑ'] },
      { char: 'ز', longPress: ['ض', 'ظ'] },
      { char: 'و', longPress: ['ۄ', 'ۆ', 'ۄٚ', 'ؤ', 'ۇ'] },
      { char: 'ه', longPress: ['ہ', 'ۂ', 'ۃ'] },
      { char: 'ع', longPress: ['ء'] },
      { char: 'ق', longPress: ['ف'] },
    ],
  ],

  // Shift / Kashmiri Vowels & Signs (Layout 2 - واول / آواز نشانہٕ)
  kashmiriVowels: [
    // Row 1: Kashmiri Vowel Signs & Wavy / Hamza marks
    [
      { char: 'ٟ', displayChar: 'بٟ', label: 'وِیوی ہمزہ زیر', isKashmiriSpecial: true },
      { char: 'ٓ', displayChar: 'بٓ', label: 'وِیوی ہمزہ پَتھ', isKashmiriSpecial: true },
      { char: 'ٕ', displayChar: 'بٕ', label: 'کٲشُر ہَمزہ تَل', isKashmiriSpecial: true },
      { char: 'ٔ', displayChar: 'بٔ', label: 'کٲشُر ہَمزہ پَتھ', isKashmiriSpecial: true },
      { char: 'ٚ', displayChar: 'بٚ', label: 'اۄلٹا وی', isKashmiriSpecial: true },
      { char: '٘', displayChar: 'ب٘', label: 'چوٹی وی', isKashmiriSpecial: true },
      { char: 'ٙ', displayChar: 'بٙ', label: 'کوچٕڑ وی', isKashmiriSpecial: true },
      { char: 'ٖ', displayChar: 'بٖ', label: 'زیر مَد', isKashmiriSpecial: true },
    ],
    // Row 2: Standard Arabic / Kashmiri Vowel Marks & Harakat
    [
      { char: 'َ', displayChar: 'بَ', label: 'زَبَر' },
      { char: 'ِ', displayChar: 'بِ', label: 'زیر' },
      { char: 'ُ', displayChar: 'بُ', label: 'پِش' },
      { char: 'ٗ', displayChar: 'بٗ', label: 'الٹا پیش' },
      { char: 'ّٰ', displayChar: 'بّٰ', label: 'خنجری الف' },
      { char: 'ْ', displayChar: 'بْ', label: 'جَزْم' },
      { char: 'ّ', displayChar: 'بّ', label: 'تَشْدِید' },
    ],
    // Row 3: Tanwin, Auxiliary signs & Urdu Punctuation
    [
      { char: 'ً', displayChar: 'بً', label: 'دُو زَبَر' },
      { char: 'ٍ', displayChar: 'بٍ', label: 'دُو زیر' },
      { char: 'ٌ', displayChar: 'بٌ', label: 'دُو پِش' },
      { char: 'ٰ', displayChar: 'بٰ', label: 'الف خنجری' },
      { char: 'ۡ', displayChar: 'بۡ', label: 'سکون صغیر' },
      { char: '۔', label: 'فُل سٹاپ' },
      { char: '؟', label: 'سوالیہ نشان' },
      { char: '،', label: 'کاما' },
      { char: '؛', label: 'سیمیکولن' },
    ],
  ],

  // Kashmiri Diacritics & Sacred Signs (Layout 3 - اِعراب)
  diacritics: [
    // Row 1: Islamic Honorific Marks (Superscript Signs)
    [
      { char: 'ﷺ', displayChar: 'ﷺ', label: 'صلی اللہ علیہ وسلم', isKashmiriSpecial: true },
      { char: 'ؐ', displayChar: 'ؐ', label: 'صلی اللہ', isKashmiriSpecial: true },
      { char: 'ؑ', displayChar: 'ؑ', label: 'علیہ السلام', isKashmiriSpecial: true },
      { char: 'ؒ', displayChar: 'ؒ', label: 'رحمہ اللہ', isKashmiriSpecial: true },
      { char: 'ؓ', displayChar: 'ؓ', label: 'رضی اللہ عنہ', isKashmiriSpecial: true },
    ],
    // Row 2: Sacred Names & Additional Marks
    [
      { char: 'ﷻ', displayChar: 'ﷻ', label: 'جل جلالہ', isKashmiriSpecial: true },
      { char: '۩', displayChar: '۩', label: 'سجدہ نشان', isKashmiriSpecial: true },
      { char: '؀', displayChar: '؀', label: 'سنہ', isKashmiriSpecial: true },
      { char: '؂', displayChar: '؂', label: 'تخلص', isKashmiriSpecial: true },
      { char: '؃', displayChar: '؃', label: 'شعري نشان', isKashmiriSpecial: true },
    ],
    // Row 3: Literary & Structural Signs
    [
      { char: 'ؔ', displayChar: 'ؔب', label: 'تخلص مارک', isKashmiriSpecial: true },
      { char: '۔', label: 'فُل سٹاپ' },
      { char: '؟', label: 'سوالیہ نشان' },
      { char: '،', label: 'کاما' },
      { char: '؛', label: 'سیمیکولن' },
    ],
  ],
  numbers: [
    [
      { char: '۱', longPress: ['1'] },
      { char: '۲', longPress: ['2'] },
      { char: '۳', longPress: ['3'] },
      { char: '۴', longPress: ['4'] },
      { char: '۵', longPress: ['5'] },
      { char: '۶', longPress: ['6'] },
      { char: '۷', longPress: ['7'] },
      { char: '۸', longPress: ['8'] },
      { char: '۹', longPress: ['9'] },
      { char: '۰', longPress: ['0'] },
    ],
    [
      { char: '،', label: 'Comma' },
      { char: '؛', label: 'Semicolon' },
      { char: '؟', label: 'Question' },
      { char: '۔', label: 'Full stop' },
      { char: '«' },
      { char: '»' },
      { char: '!' },
      { char: ':' },
      { char: '-' },
      { char: '+' },
    ],
  ],
};

// Kashmir Art & Calligraphy Stickers / Motifs (Vector paths or text glyphs)
export const KASHMIRI_STICKERS = [
  { id: 'chinar-leaf', name: 'Chinar Leaf (بونہٕ پَن)', icon: 'Leaf', preview: '🍁' },
  { id: 'bismillah', name: 'Bismillah Calligraphy', icon: 'Sparkles', preview: '﷽' },
  { id: 'durood', name: 'Durood Sharif', icon: 'Star', preview: 'ﷺ' },
  { id: 'jallajalaluhu', name: 'Jalla Jalaluhu', icon: 'Shield', preview: 'ﷻ' },
  { id: 'kashmir-callig', name: 'Kashmir Calligraphy', icon: 'PenTool', preview: 'کٔشیٖر' },
  { id: 'takhallus', name: 'Poetic Marker', icon: 'Feather', preview: '؂' },
  { id: 'flower', name: 'Kashmiri Kong Posh (Saffron)', icon: 'Flower2', preview: '🌸' },
  { id: 'crescent', name: 'Islamic Crescent', icon: 'Moon', preview: '🌙' },
  { id: 'lantern', name: 'Traditional Tsong / Lamp', icon: 'Flame', preview: '🪔' },
  { id: 'mountain', name: 'Himalayan / Pir Panjal', icon: 'Mountain', preview: '🏔️' },
];

// Aesthetic Kashmiri Background Themes & Palettes
export const KASHMIRI_PALETTES = [
  {
    id: 'saffron-dusk',
    name: 'Saffron Dusk (زَعفران / کۄنگ)',
    gradient: 'from-amber-600 via-orange-800 to-stone-950',
    color: '#d97706',
    textColor: '#ffffff',
  },
  {
    id: 'chinar-crimson',
    name: 'Chinar Crimson (بونہٕ رنگ)',
    gradient: 'from-red-800 via-rose-950 to-stone-950',
    color: '#991b1b',
    textColor: '#ffffff',
  },
  {
    id: 'dal-lake-emerald',
    name: 'Dal Lake Emerald (ڈَل سَر)',
    gradient: 'from-emerald-700 via-teal-900 to-stone-950',
    color: '#047857',
    textColor: '#ffffff',
  },
  {
    id: 'kashmiri-slate',
    name: 'Kashmiri Slate & Walnut (دوانکٔنٛد)',
    gradient: 'from-stone-800 via-stone-900 to-stone-950',
    color: '#292524',
    textColor: '#fafaf9',
  },
  {
    id: 'pir-panjal-snow',
    name: 'Pir Panjal Mist (پیر پَنچال)',
    gradient: 'from-slate-100 via-stone-200 to-amber-50',
    color: '#f5f5f4',
    textColor: '#1c1917',
  },
  {
    id: 'royal-pashmina',
    name: 'Royal Pashmina (پَشمِینہٕ)',
    gradient: 'from-amber-900 via-yellow-950 to-stone-950',
    color: '#78350f',
    textColor: '#fef3c7',
  },
  {
    id: 'islamic-teal',
    name: 'Khatamband Teal (خَتَم بَنٛد)',
    gradient: 'from-cyan-900 via-teal-950 to-stone-950',
    color: '#164e63',
    textColor: '#ffffff',
  },
];

export const QUICK_KASHMIRI_BAR = [
  { char: 'ٲ', name: 'ٲ' },
  { char: 'ٳ', name: 'ٳ' },
  { char: 'ۄ', name: 'ۄ' },
  { char: 'ۆ', name: 'ۆ' },
  { char: 'ؠ', name: 'ؠ' },
  { char: 'ٕ', name: 'ٕ' },
  { char: 'ژ', name: 'ژ' },
  { char: 'ٹ', name: 'ٹ' },
  { char: 'ڈ', name: 'ڈ' },
  { char: 'ڑ', name: 'ڑ' },
  { char: 'ں', name: 'ں' },
  { char: 'ھ', name: 'ھ' },
  { char: 'َ', name: 'َ' },
  { char: 'ِ', name: 'ِ' },
  { char: 'ُ', name: 'ُ' },
  { char: 'ْ', name: 'ْ' },
  { char: 'ّ', name: 'ّ' },
  { char: 'ٚ', name: 'ٚ' },
  { char: 'ٔ', name: 'ٔ' },
];

