import {
  CanvasPreset,
  KashmiriCharInfo,
  KashurTemplate,
  KeyboardKey,
  TextStyleProperties
} from '../types';

export const DEFAULT_TEXT_STYLE: TextStyleProperties = {
  fontFamily: 'Noto Nastaliq Urdu',
  fontSize: 12,
  bold: false,
  italic: false,
  underline: false,
  color: '#1c1917', // stone-900
  align: 'right',
  verticalAlign: 'top',
  lineHeight: 2.2,
  letterSpacing: 0,
  direction: 'rtl',
  opacity: 1,
};

// Comprehensive Canvas & Document Presets for Kashmiri Studio
export const CANVAS_PRESETS: CanvasPreset[] = [
  // --- Big & Standard Document / Print Paper Sizes (Exclusive for PDF, DOCX, Official Docs) ---
  {
    id: 'a4',
    name: 'A4 Standard Document',
    nameKashmiri: 'اے فور دستاویز (A4)',
    width: 1240,
    height: 1754,
    aspectRatio: '1/1.414',
    icon: 'FileText',
    description: 'معیاری دفتری دستاویز، خط، نوٹس و کتابی صفحہ (PDF & DOCX Default)',
    dimensionsMm: '210 × 297 mm',
    category: 'document',
  },
  {
    id: 'a3',
    name: 'A3 Broadside / Poster',
    nameKashmiri: 'اے تھری بڑا پوسٹر (A3)',
    width: 1754,
    height: 2480,
    aspectRatio: '1/1.414',
    icon: 'Maximize2',
    description: 'بڑا کشمیری اخباری صفحہ، دیوار پوسٹر و بڑا نوٹس (Broadside)',
    dimensionsMm: '297 × 420 mm',
    category: 'document',
  },
  {
    id: 'letter',
    name: 'US Letter Document',
    nameKashmiri: 'یو ایس لیٹر (Letter)',
    width: 1275,
    height: 1650,
    aspectRatio: '8.5/11',
    icon: 'FileText',
    description: 'معیاری امریکی دفتری مکتوب و دستاویز',
    dimensionsMm: '215.9 × 279.4 mm',
    category: 'document',
  },
  {
    id: 'legal',
    name: 'US Legal Document',
    nameKashmiri: 'قانونی مکتوب (Legal)',
    width: 1275,
    height: 2100,
    aspectRatio: '8.5/14',
    icon: 'FileSpreadsheet',
    description: 'عدالتی و قانونی معاہدات، طویل دفتری ریکارڈز',
    dimensionsMm: '215.9 × 355.6 mm',
    category: 'document',
  },
  {
    id: 'tabloid',
    name: 'Tabloid Newspaper',
    nameKashmiri: 'ٹیبلوئڈ جریدہ (Tabloid)',
    width: 1650,
    height: 2550,
    aspectRatio: '11/17',
    icon: 'Newspaper',
    description: 'کشمیری ہفت روزہ اخبار، میگزین سرورق و ادبی جریدہ',
    dimensionsMm: '279.4 × 431.8 mm',
    category: 'document',
  },
  {
    id: 'b4',
    name: 'B4 Academic Journal',
    nameKashmiri: 'بی فور جریدہ (B4)',
    width: 1476,
    height: 2083,
    aspectRatio: '1/1.414',
    icon: 'BookOpen',
    description: 'علمی رسالہ، ادبی مجلہ و تحقیقی مقالہ',
    dimensionsMm: '250 × 353 mm',
    category: 'document',
  },
  {
    id: 'b5',
    name: 'B5 Literary Edition / Book',
    nameKashmiri: 'بی فائیو کتاب (B5)',
    width: 1039,
    height: 1476,
    aspectRatio: '1/1.414',
    icon: 'Book',
    description: 'کشمیری شاعری دیوان، افسانہ و درسی کتابی سائز',
    dimensionsMm: '176 × 250 mm',
    category: 'document',
  },

  // --- Medium & Lower / Pocket Print Sizes ---
  {
    id: 'a5',
    name: 'A5 Booklet / Diary',
    nameKashmiri: 'اے فائیو کتابچہ (A5)',
    width: 874,
    height: 1240,
    aspectRatio: '1/1.414',
    icon: 'BookOpen',
    description: 'مختصر کتابچہ، ذاتی ڈائری، کلامِ لَل دؠد و غزل بیاض',
    dimensionsMm: '148 × 210 mm',
    category: 'print',
  },
  {
    id: 'a6',
    name: 'A6 Pocket Card',
    nameKashmiri: 'اے سکس جیبی کارڈ (A6)',
    width: 620,
    height: 874,
    aspectRatio: '1/1.414',
    icon: 'CreditCard',
    description: 'مختصر جیبی کارڈ، دعائیہ پمفلٹ و پوسٹ کارڈ',
    dimensionsMm: '105 × 148 mm',
    category: 'print',
  },
  {
    id: 'b6',
    name: 'B6 Pocket Book',
    nameKashmiri: 'بی سکس مختصر کتاب (B6)',
    width: 738,
    height: 1039,
    aspectRatio: '1/1.414',
    icon: 'Bookmark',
    description: 'مختصر جیبی اشاعت و دعائیہ مجموعہ',
    dimensionsMm: '125 × 176 mm',
    category: 'print',
  },

  // --- Digital, Social Media & Visual Poetry Cards ---
  {
    id: '1:1',
    name: 'Square Post',
    nameKashmiri: 'مورَبَع کارڈ (1:1)',
    width: 1080,
    height: 1080,
    aspectRatio: '1/1',
    icon: 'Square',
    description: 'انسٹاگرام پوسٹ، واٹس ایپ پروفائل و کشمیری شاعری کارڈ',
    dimensionsMm: '1080 × 1080 px',
    category: 'social',
  },
  {
    id: '4:5',
    name: 'Portrait Feed',
    nameKashmiri: 'عمودی فیڈ (4:5)',
    width: 1080,
    height: 1350,
    aspectRatio: '4/5',
    icon: 'RectangleVertical',
    description: 'انسٹاگرام عمودی پوسٹ و فیس بک فیڈ کارڈ',
    dimensionsMm: '1080 × 1350 px',
    category: 'social',
  },
  {
    id: '9:16',
    name: 'Story & Status',
    nameKashmiri: 'سٹوری و سٹیٹس (9:16)',
    width: 1080,
    height: 1920,
    aspectRatio: '9/16',
    icon: 'Smartphone',
    description: 'واٹس ایپ سٹیٹس، انسٹاگرام سٹوری، ریلز و ٹک ٹاک',
    dimensionsMm: '1080 × 1920 px',
    category: 'social',
  },
  {
    id: '16:9',
    name: 'Landscape Banner',
    nameKashmiri: 'افقی بینر (16:9)',
    width: 1920,
    height: 1080,
    aspectRatio: '16/9',
    icon: 'Monitor',
    description: 'یوٹیوب تھمب نیل، ویب سائٹ بینر و ٹی وی پریزنٹیشن',
    dimensionsMm: '1920 × 1080 px',
    category: 'social',
  },
  {
    id: '3:4',
    name: 'Classic Frame',
    nameKashmiri: 'کلاسیک فریم (3:4)',
    width: 1200,
    height: 1600,
    aspectRatio: '3/4',
    icon: 'Frame',
    description: 'کلاسیک پورٹریٹ، فریم شدہ خطاطی و تصویری پوسٹر',
    dimensionsMm: '1200 × 1600 px',
    category: 'social',
  },
  {
    id: '2:3',
    name: 'Photo Print',
    nameKashmiri: 'فوٹو پرنٹ (2:3)',
    width: 1200,
    height: 1800,
    aspectRatio: '2/3',
    icon: 'Image',
    description: 'معیاری فوٹو گرافی پرنٹ و خطاطی کارڈ',
    dimensionsMm: '1200 × 1800 px',
    category: 'social',
  },
  {
    id: 'auto',
    name: 'Flowing Document',
    nameKashmiri: 'آزاد مسودہ (Continuous)',
    width: 1200,
    height: 1600,
    aspectRatio: 'auto',
    icon: 'Maximize2',
    description: 'لامحدود بہاؤ کے ساتھ آزادانہ کٲشُر تحریر و مقالہ',
    dimensionsMm: 'Auto Height',
    category: 'social',
  },
];

// Complete Kashmiri Character Database
export const KASHMIRI_CHARACTERS_DB: KashmiriCharInfo[] = [
  // Kashmiri Specific Vowels & Letters
  {
    char: 'ٲ',
    name: 'Kashmiri Alif with Madda',
    nameKashmiri: 'ٲلِف مَدٕ',
    unicodeHex: 'U+0672',
    category: 'vowel',
    sound: 'Open-mid back unrounded vowel [ʌ] / [ɔ]',
    exampleWord: 'ٲسۍ',
    exampleMeaning: 'We / Us (Aesy)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ٳ',
    name: 'Kashmiri Alif with Hamza below',
    nameKashmiri: 'ٳلِف تَلی ہَمزَہ',
    unicodeHex: 'U+0673',
    category: 'vowel',
    sound: 'Close central unrounded vowel [ɨ] / [ɯ]',
    exampleWord: 'ٳنٛسان',
    exampleMeaning: 'Human (Insaan variant)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ۄ',
    name: 'Kashmiri Waw with Ring',
    nameKashmiri: 'حَلقہٕ دار واو',
    unicodeHex: 'U+06C4',
    category: 'vowel',
    sound: 'Open-mid back rounded vowel [ɔ]',
    exampleWord: 'ۄپھُن',
    exampleMeaning: 'To fly (Wophun)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ۄٚ',
    name: 'Kashmiri Waw with Inverted V',
    nameKashmiri: 'واو پؠٹھ اۄلٹا وی',
    unicodeHex: 'U+06C4 + U+065A',
    category: 'vowel',
    sound: 'Short rounded vowel [ŏ]',
    exampleWord: 'کۄٚل',
    exampleMeaning: 'Stream / Canal (Kol)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ۆ',
    name: 'Kashmiri Waw with V / Caron',
    nameKashmiri: 'واو پؠٹھ وی',
    unicodeHex: 'U+06C6',
    category: 'vowel',
    sound: 'Close-mid back rounded vowel [o]',
    exampleWord: 'ۆل',
    exampleMeaning: 'Nest (Ol)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ؠ',
    name: 'Kashmiri Yeh (Tshae / Tse)',
    nameKashmiri: 'کٲشُر یے (چھٔ)',
    unicodeHex: 'U+0620',
    category: 'letter',
    sound: 'Palatalized semi-vowel / Kashmiri distinct sound [ʲ] / [j]',
    exampleWord: 'دٔلیٖل',
    exampleMeaning: 'Story / Tale (Daleel)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ےٚ',
    name: 'Kashmiri Bari Ye with Inverted V',
    nameKashmiri: 'بٔڑی یے پؠٹھ اۄلٹا وی',
    unicodeHex: 'U+06D2 + U+065A',
    category: 'vowel',
    sound: 'Short front vowel [ĕ]',
    exampleWord: 'مےٚ',
    exampleMeaning: 'Me / To me (Me)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ێ',
    name: 'Kashmiri Yeh with Inverted V above',
    nameKashmiri: 'یے پؠٹھ وی',
    unicodeHex: 'U+06CE',
    category: 'letter',
    sound: 'Kashmiri vowel Yeh',
    exampleWord: 'سێند',
    exampleMeaning: 'River / Indus variant',
    isKashmiriSpecific: true,
  },
  // Diacritics
  {
    char: 'َ',
    name: 'Zabar (Fatha)',
    nameKashmiri: 'زَبَر (فَتحَہ)',
    unicodeHex: 'U+064E',
    category: 'diacritic',
    sound: 'Short "a" vowel sound [a]',
    exampleWord: 'کَر',
    exampleMeaning: 'Do (Kar)',
  },
  {
    char: 'ِ',
    name: 'Zer (Kasra)',
    nameKashmiri: 'زیر (کَسرَہ)',
    unicodeHex: 'U+0650',
    category: 'diacritic',
    sound: 'Short "i" vowel sound [i]',
    exampleWord: 'دِل',
    exampleMeaning: 'Heart (Dil)',
  },
  {
    char: 'ُ',
    name: 'Pesh (Damma)',
    nameKashmiri: 'پیش (ضَمَہ)',
    unicodeHex: 'U+064F',
    category: 'diacritic',
    sound: 'Short "u" vowel sound [u]',
    exampleWord: 'پُل',
    exampleMeaning: 'Bridge (Pul)',
  },
  {
    char: 'ْ',
    name: 'Jazm / Sukun',
    nameKashmiri: 'جَزم / سُکون',
    unicodeHex: 'U+0652',
    category: 'diacritic',
    sound: 'Vowelless marker',
    exampleWord: 'سَردْ',
    exampleMeaning: 'Cold',
  },
  {
    char: 'ّ',
    name: 'Tashdeed (Shaddah)',
    nameKashmiri: 'تَشدِید',
    unicodeHex: 'U+0651',
    category: 'diacritic',
    sound: 'Consonant gemination (doubling)',
    exampleWord: 'اَچّھ',
    exampleMeaning: 'Eye (Achh)',
  },
  {
    char: '٘',
    name: 'Kashmiri Small High V',
    nameKashmiri: 'چھۄٹ وی اِعراب',
    unicodeHex: 'U+0658',
    category: 'combining',
    sound: 'Kashmiri specific vowel modifier',
    exampleWord: 'گ٘رٛانٛد',
    exampleMeaning: 'Counting (Grand)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ٚ',
    name: 'Kashmiri Small High Inverted V',
    nameKashmiri: 'اۄلٹٕ وی اِعراب',
    unicodeHex: 'U+065A',
    category: 'combining',
    sound: 'Kashmiri short vowel diacritic',
    exampleWord: 'تٚر',
    exampleMeaning: 'Float / Cross',
    isKashmiriSpecific: true,
  },
  {
    char: 'ٔ',
    name: 'Hamza Above',
    nameKashmiri: 'ہَمزَہ پؠٹھ',
    unicodeHex: 'U+0654',
    category: 'combining',
    sound: 'Kashmiri short high vowel / vocalic break',
    exampleWord: 'پٔز',
    exampleMeaning: 'Truth / Real (Paez)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ٕ',
    name: 'Hamza Below',
    nameKashmiri: 'ہَمزَہ تَل',
    unicodeHex: 'U+0655',
    category: 'combining',
    sound: 'Kashmiri central vowel [ɨ]',
    exampleWord: 'سٕریٖنَگَر',
    exampleMeaning: 'Srinagar (city of Kashmir)',
    isKashmiriSpecific: true,
  },
  {
    char: 'ٖ',
    name: 'Khadi Zer (Subscript Alef)',
    nameKashmiri: 'کھٔڑی زیر',
    unicodeHex: 'U+0656',
    category: 'diacritic',
    sound: 'Long "ee" vowel',
    exampleWord: 'بِہٖ',
    exampleMeaning: 'With Him',
  },
  {
    char: 'ٗ',
    name: 'Ulta Pesh (Inverted Damma)',
    nameKashmiri: 'اۄلٹٕ پیش',
    unicodeHex: 'U+0657',
    category: 'diacritic',
    sound: 'Long "oo" sound',
    exampleWord: 'لَہٗ',
    exampleMeaning: 'For Him',
  },
  {
    char: 'ٰ',
    name: 'Khada Zabar (Superscript Alef)',
    nameKashmiri: 'کھڑا زَبَر',
    unicodeHex: 'U+0670',
    category: 'diacritic',
    sound: 'Long "aa" vowel',
    exampleWord: 'عیسیٰ',
    exampleMeaning: 'Isa (Jesus)',
  },
  {
    char: 'ں',
    name: 'Noon Ghunna',
    nameKashmiri: 'نُون غُنَہ',
    unicodeHex: 'U+06BA',
    category: 'letter',
    sound: 'Nasalization',
    exampleWord: 'ماں',
    exampleMeaning: 'Mother',
  },
  {
    char: 'ژ',
    name: 'Tcheh / Jeem with 3 dots',
    nameKashmiri: 'ژے (ژ)',
    unicodeHex: 'U+0698',
    category: 'letter',
    sound: 'Voiceless alveolar affricate [ts]',
    exampleWord: 'ژۄنٛگ',
    exampleMeaning: 'Lamp (Tsong)',
    isKashmiriSpecific: true,
  },
  {
    char: 'چ',
    name: 'Che',
    nameKashmiri: 'چے',
    unicodeHex: 'U+0686',
    category: 'letter',
    sound: '[tʃ]',
    exampleWord: 'چائے',
    exampleMeaning: 'Tea (Chai)',
  },
  {
    char: 'پ',
    name: 'Pe',
    nameKashmiri: 'پے',
    unicodeHex: 'U+067E',
    category: 'letter',
    sound: '[p]',
    exampleWord: 'پَنُن',
    exampleMeaning: 'Own (Panun)',
  },
  {
    char: 'ٹ',
    name: 'Tte',
    nameKashmiri: 'ٹے',
    unicodeHex: 'U+0679',
    category: 'letter',
    sound: 'Retroflex [ʈ]',
    exampleWord: 'ٹاٹھیٖ',
    exampleMeaning: 'Dear (Taathi)',
  },
  {
    char: 'ڈ',
    name: 'Ddal',
    nameKashmiri: 'ڈال',
    unicodeHex: 'U+0688',
    category: 'letter',
    sound: 'Retroflex [ɖ]',
    exampleWord: 'ڈَل',
    exampleMeaning: 'Dal Lake',
  },
  {
    char: 'ڑ',
    name: 'Rre',
    nameKashmiri: 'ڑے',
    unicodeHex: 'U+0691',
    category: 'letter',
    sound: 'Retroflex flap [ɽ]',
    exampleWord: 'گٲڑِ',
    exampleMeaning: 'Fish / Car (Gaadi)',
  },
  {
    char: 'ھ',
    name: 'Dochashmi He',
    nameKashmiri: 'دو چَشمی ہے',
    unicodeHex: 'U+06BE',
    category: 'letter',
    sound: 'Aspiration marker (bh, ph, th, etc.)',
    exampleWord: 'گھَر',
    exampleMeaning: 'Home (Ghar)',
  },
  {
    char: 'ہ',
    name: 'Goal He',
    nameKashmiri: 'گول ہے',
    unicodeHex: 'U+06C1',
    category: 'letter',
    sound: '[h]',
    exampleWord: 'ہَوا',
    exampleMeaning: 'Air / Breeze',
  },
  {
    char: 'ے',
    name: 'Bari Ye',
    nameKashmiri: 'بٔڑی یے',
    unicodeHex: 'U+06D2',
    category: 'letter',
    sound: 'Long "e" vowel [eː]',
    exampleWord: 'سارِوٕے',
    exampleMeaning: 'All (Saarwi)',
  },
];

// Dedicated Keyboard Layouts - Clean, non-duplicated Kashmiri & Perso-Arabic layout
export const KASHMIRI_KEYBOARD_LAYOUTS = {
  // Main letters (Layout 1 - حروف) - Clean, zero-duplication standard & Kashmiri letters prioritized
  main: [
    // Row 1: Kashmiri Primary Vowels & Top Consonants
    [
      { char: 'ٲ', isKashmiriSpecial: true, label: 'Alif Madda', longPress: ['ٳ'] },
      { char: 'ۄ', isKashmiriSpecial: true, label: 'Waw Ring', longPress: ['ۄٚ', 'ۆ'] },
      { char: 'ؠ', isKashmiriSpecial: true, label: 'Tshae Yeh', longPress: ['ےٚ', 'ێ'] },
      { char: 'ژ', isKashmiriSpecial: true, label: 'Tse' },
      { char: 'چ', label: 'Tche', longPress: ['چھ'] },
      { char: 'پ', label: 'Pe', longPress: ['پھ'] },
      { char: 'ٹ', label: 'Tte', longPress: ['ٹھ'] },
      { char: 'ت', label: 'Te', longPress: ['تھ', 'ط', 'ۃ'] },
      { char: 'ڈ', label: 'Ddal', longPress: ['ڈھ'] },
      { char: 'د', label: 'Dal', longPress: ['دھ', 'ذ'] },
      { char: 'ھ', label: 'Do-chashmi' },
    ],
    // Row 2: Home Row Consonants
    [
      { char: 'ش', label: 'Sheen' },
      { char: 'س', label: 'Seen', longPress: ['ص', 'ث'] },
      { char: 'ی', label: 'Chhoti Yeh', longPress: ['ئ'] },
      { char: 'ب', label: 'Be', longPress: ['بھ'] },
      { char: 'ل', label: 'Laam', longPress: ['لا', 'لٲ'] },
      { char: 'ا', label: 'Alif', longPress: ['آ', 'أ', 'إ', 'ٱ'] },
      { char: 'ن', label: 'Noon', longPress: ['ں', 'ݨ'] },
      { char: 'م', label: 'Meem' },
      { char: 'ک', label: 'Kaaf', longPress: ['کھ'] },
      { char: 'گ', label: 'Gaaf', longPress: ['گھ'] },
      { char: 'ر', label: 'Re' },
    ],
    // Row 3: Bottom Row Consonants & Key Vowel Forms
    [
      { char: 'ف', label: 'Fe', longPress: ['ڤ'] },
      { char: 'غ', label: 'Ghain' },
      { char: 'ح', label: 'Bari He', longPress: ['خ'] },
      { char: 'ج', label: 'Jeem', longPress: ['جھ'] },
      { char: 'ز', label: 'Ze', longPress: ['ض', 'ظ'] },
      { char: 'ڑ', label: 'Rre' },
      { char: 'و', label: 'Waw', longPress: ['ؤ', 'ۇ'] },
      { char: 'ہ', label: 'Goal He', longPress: ['ۂ'] },
      { char: 'ع', label: 'Ain', longPress: ['ء'] },
      { char: 'ق', label: 'Qaaf' },
      { char: 'ے', label: 'Bari Yeh' },
    ],
  ],

  // Kashmiri Vowels & Diacritic Harakat (Layout 2 - واول و اِعراب)
  kashmiriVowels: [
    // Row 1: Kashmiri Vowel Diacritics (Crucial for Nastaliq positioning)
    [
      { char: 'ٔ', displayChar: '◌ٔ', label: 'کٲشُر ہَمزہ پَتھ', isKashmiriSpecial: true },
      { char: 'ٕ', displayChar: '◌ٕ', label: 'کٲشُر ہَمزہ تَل', isKashmiriSpecial: true },
      { char: 'ٚ', displayChar: '◌ٚ', label: 'اۄلٹا وی (Inverted V)', isKashmiriSpecial: true },
      { char: '٘', displayChar: '◌٘', label: 'چوٹی وی (Small V)', isKashmiriSpecial: true },
      { char: 'ٖ', displayChar: '◌ٖ', label: 'زیر مَد (Subscript Alef)', isKashmiriSpecial: true },
      { char: 'ٗ', displayChar: '◌ٗ', label: 'الٹا پیش (Inverted Damma)', isKashmiriSpecial: true },
      { char: 'ٟ', displayChar: '◌ٟ', label: 'وِیوی ہمزہ زیر', isKashmiriSpecial: true },
      { char: 'ٓ', displayChar: '◌ٓ', label: 'مَدٕ (Madd)', isKashmiriSpecial: true },
    ],
    // Row 2: Traditional Arabic & Persian Harakat
    [
      { char: 'َ', displayChar: '◌َ', label: 'زَبَر (Zabar / Fatha)' },
      { char: 'ِ', displayChar: '◌ِ', label: 'زیر (Zer / Kasra)' },
      { char: 'ُ', displayChar: '◌ُ', label: 'پِش (Pesh / Damma)' },
      { char: 'ْ', displayChar: '◌ْ', label: 'جَزْم / سُکون (Jazm)' },
      { char: 'ّ', displayChar: '◌ّ', label: 'تَشْدِید (Tashdeed)' },
      { char: 'ٰ', displayChar: '◌ٰ', label: 'الف خنجری (Superscript Alef)' },
      { char: 'ّٰ', displayChar: '◌ّٰ', label: 'خنجری الف تشدید' },
      { char: 'ۡ', displayChar: '◌ۡ', label: 'سکون صغیر' },
    ],
    // Row 3: Full Kashmiri Vowel Matras & Tanween
    [
      { char: 'اَ', displayChar: 'اَ', label: 'Short A' },
      { char: 'اِ', displayChar: 'اِ', label: 'Short I' },
      { char: 'اُ', displayChar: 'اُ', label: 'Short U' },
      { char: 'ایٖ', displayChar: 'ایٖ', label: 'Long Ee', isKashmiriSpecial: true },
      { char: 'اوٗ', displayChar: 'اوٗ', label: 'Long Oo', isKashmiriSpecial: true },
      { char: 'ً', displayChar: '◌ً', label: 'دو زبر (Tanwin Fath)' },
      { char: 'ٍ', displayChar: '◌ٍ', label: 'دو زیر (Tanwin Kasr)' },
      { char: 'ٌ', displayChar: '◌ٌ', label: 'دو پیش (Tanwin Damm)' },
    ],
  ],

  // Kashmiri Diacritics & Sacred Signs (Layout 3 - اِعراب و رموز)
  diacritics: [
    // Row 1: Sacred Calligraphy & Quranic Marks
    [
      { char: '﷽', displayChar: '﷽', label: 'بسم اللہ', isKashmiriSpecial: true },
      { char: 'ﷺ', displayChar: 'ﷺ', label: 'درود شریف', isKashmiriSpecial: true },
      { char: 'ﷻ', displayChar: 'ﷻ', label: 'جل جلالہ', isKashmiriSpecial: true },
      { char: 'ؐ', displayChar: 'ؐ', label: 'صلی اللہ' },
      { char: 'ؑ', displayChar: 'ؑ', label: 'علیہ السلام' },
      { char: 'ؒ', displayChar: 'ؒ', label: 'رحمہ اللہ' },
      { char: 'ؓ', displayChar: 'ؓ', label: 'رضی اللہ' },
      { char: '۞', displayChar: '۞', label: 'حزب آیت' },
      { char: '۝', displayChar: '۝', label: 'آیت نشان' },
      { char: '۩', displayChar: '۩', label: 'سجدہ نشان' },
    ],
    // Row 2: Traditional Poetic, Literary & Editorial Signs
    [
      { char: '؎', displayChar: '؎', label: 'شعر نشان', isKashmiriSpecial: true },
      { char: '؏', displayChar: '؏', label: 'مصرعہ نشان', isKashmiriSpecial: true },
      { char: '؂', displayChar: '؂', label: 'تخلص نشان', isKashmiriSpecial: true },
      { char: '؀', displayChar: '؀', label: 'نمبر نشان' },
      { char: '؁', displayChar: '؁', label: 'سنہ نشان' },
      { char: '؍', displayChar: '؍', label: 'تاریخ نشان' },
      { char: '؃', displayChar: '؃', label: 'صفحہ نشان' },
      { char: '؞', displayChar: '؞', label: 'تین نکتے' },
      { char: 'ـ', displayChar: 'ـ', label: 'کشیدہ/تطویل' },
      { char: '…', displayChar: '…', label: 'تین نقطے (حذف)' },
    ],
    // Row 3: Brackets, Quotation Marks & Typographic Symbols
    [
      { char: '﴾', displayChar: '﴾', label: 'قرآنی بریکٹ' },
      { char: '﴿', displayChar: '﴿', label: 'قرآنی بریکٹ' },
      { char: '«', displayChar: '«', label: 'گیلو میں' },
      { char: '»', displayChar: '»', label: 'گیلو میں' },
      { char: '“', displayChar: '“', label: 'ڈبل کوٹ' },
      { char: '”', displayChar: '”', label: 'ڈبل کوٹ' },
      { char: '‘', displayChar: '‘', label: 'سنگل کوٹ' },
      { char: '’', displayChar: '’', label: 'سنگل کوٹ' },
      { char: '٭', displayChar: '٭', label: 'ستارہ' },
      { char: '※', displayChar: '※', label: 'حوالہ' },
      { char: '•', displayChar: '•', label: 'بلٹ' },
    ],
  ],

  // Numbers and Symbols (Layout 4 - ۱۲۳ و علامات)
  numbers: [
    // Row 1: Kashmiri / Urdu Numerals with Latin Long-press
    [
      { char: '۱', label: '1', longPress: ['1'] },
      { char: '۲', label: '2', longPress: ['2'] },
      { char: '۳', label: '3', longPress: ['3'] },
      { char: '۴', label: '4', longPress: ['4'] },
      { char: '۵', label: '5', longPress: ['5'] },
      { char: '۶', label: '6', longPress: ['6'] },
      { char: '۷', label: '7', longPress: ['7'] },
      { char: '۸', label: '8', longPress: ['8'] },
      { char: '۹', label: '9', longPress: ['9'] },
      { char: '۰', label: '0', longPress: ['0'] },
    ],
    // Row 2: Standard Kashmiri, Urdu & Regional Punctuation
    [
      { char: '۔', label: 'Full Stop' },
      { char: '،', label: 'Comma' },
      { char: '؟', label: 'Question' },
      { char: '؛', label: 'Semicolon' },
      { char: ':', label: 'Colon' },
      { char: '!', label: 'Exclamation' },
      { char: '—', label: 'Em Dash' },
      { char: '-', label: 'Hyphen' },
      { char: '/', label: 'Slash' },
      { char: '\\', label: 'Backslash' },
      { char: '٪', label: 'Percent' },
    ],
    // Row 3: Math, Brackets & Currency
    [
      { char: '(', label: 'Bracket (' },
      { char: ')', label: 'Bracket )' },
      { char: '[', label: 'Square [' },
      { char: ']', label: 'Square ]' },
      { char: '{', label: 'Brace {' },
      { char: '}', label: 'Brace }' },
      { char: '+', label: 'Plus' },
      { char: '×', label: 'Multiply' },
      { char: '÷', label: 'Divide' },
      { char: '=', label: 'Equals' },
      { char: '₹', label: 'Rupee' },
      { char: '$', label: 'Dollar' },
    ],
  ],
};

// Kashmir Art & Calligraphy Stickers / Motifs (Vector paths or text glyphs)
export const KASHMIRI_STICKERS = [
  { id: 'chinar-leaf', name: 'Chinar Leaf (بونہٕ پَن)', icon: 'Leaf', preview: '🍁' },
  { id: 'bismillah', name: 'Bismillah Calligraphy', icon: 'Sparkles', preview: '﷽' },
  { id: 'durood', name: 'Durood Sharif', icon: 'Star', preview: 'ﷺ' },
  { id: 'jallajalaluhu', name: 'Jalla Jalaluhu', icon: 'Shield', preview: 'ﷻ' },
  { id: 'kashmir-callig', name: 'Kashmir Calligraphy', icon: 'PenTool', preview: 'کٔشیٖر' },
  { id: 'takhallus', name: 'Poetic Marker', icon: 'Feather', preview: '؂' },
  { id: 'flower', name: 'Kashmiri Kong Posh (Saffron)', icon: 'Flower2', preview: '🌸' },
  { id: 'crescent', name: 'Islamic Crescent', icon: 'Moon', preview: '🌙' },
  { id: 'lantern', name: 'Traditional Tsong / Lamp', icon: 'Flame', preview: '🪔' },
  { id: 'mountain', name: 'Himalayan / Pir Panjal', icon: 'Mountain', preview: '🏔️' },
];

// Comprehensive Solid Color Palettes
export interface ColorSwatch {
  name: string;
  color: string;
}

export interface PaletteGroup {
  id: string;
  name: string;
  swatches: ColorSwatch[];
}

export const SOLID_PALETTE_GROUPS: PaletteGroup[] = [
  {
    id: 'heritage',
    name: 'Kashmiri Heritage (کٲشُر وِرثہٕ)',
    swatches: [
      { name: 'Saffron Gold (کۄنگ)', color: '#d97706' },
      { name: 'Chinar Crimson (بونہٕ رنگ)', color: '#991b1b' },
      { name: 'Dal Emerald (ڈَل سَر)', color: '#047857' },
      { name: 'Walnut Wood (دوان)', color: '#451a03' },
      { name: 'Pashmina Cream (پَشمِینہٕ)', color: '#fef3c7' },
      { name: 'Pir Panjal Slate (پیر پَنچال)', color: '#334155' },
      { name: 'Khatamband Teal (خَتَم بَنٛد)', color: '#0f766e' },
      { name: 'Mughal Blue (شاہی نیول)', color: '#1e3a8a' },
      { name: 'Gulab Rose (گُلاب)', color: '#be185d' },
      { name: 'Charcoal Obsidian (سیاہ)', color: '#18181b' },
      { name: 'Almond Tan (بادام)', color: '#b45309' },
      { name: 'Willow Sage (ویر)', color: '#65a30d' },
    ],
  },
  {
    id: 'vibrant',
    name: 'Vibrant & Modern (روشن)',
    swatches: [
      { name: 'Ruby Red', color: '#dc2626' },
      { name: 'Sunset Orange', color: '#ea580c' },
      { name: 'Solar Amber', color: '#f59e0b' },
      { name: 'Leaf Green', color: '#16a34a' },
      { name: 'Forest Green', color: '#15803d' },
      { name: 'Cyan Sky', color: '#0891b2' },
      { name: 'Electric Azure', color: '#0284c7' },
      { name: 'Indigo Velvet', color: '#4338ca' },
      { name: 'Vivid Violet', color: '#7c3aed' },
      { name: 'Hot Magenta', color: '#c026d3' },
      { name: 'Rose Pink', color: '#e11d48' },
      { name: 'Coral Flame', color: '#f43f5e' },
    ],
  },
  {
    id: 'monochrome',
    name: 'Monochrome & Earthy (قدرتی)',
    swatches: [
      { name: 'Pitch Black', color: '#000000' },
      { name: 'Dark Obsidian', color: '#1c1917' },
      { name: 'Slate 800', color: '#1e293b' },
      { name: 'Charcoal 700', color: '#334155' },
      { name: 'Steel 500', color: '#64748b' },
      { name: 'Stone 400', color: '#a8a29e' },
      { name: 'Warm Parchment', color: '#fdfbf7' },
      { name: 'Pure White', color: '#ffffff' },
      { name: 'Sandstone Ochre', color: '#78350f' },
      { name: 'Raw Umber', color: '#57534e' },
      { name: 'Linen Soft', color: '#f5f5f4' },
      { name: 'Silver Mist', color: '#e2e8f0' },
    ],
  },
  {
    id: 'pastel',
    name: 'Pastel & Gentle (نَرم رنگ)',
    swatches: [
      { name: 'Blush Rose', color: '#fecdd3' },
      { name: 'Warm Peach', color: '#ffedd5' },
      { name: 'Pale Saffron', color: '#fef3c7' },
      { name: 'Butter Cream', color: '#fef9c3' },
      { name: 'Mint Breeze', color: '#dcfce7' },
      { name: 'Teal Foam', color: '#ccfbf1' },
      { name: 'Sky Frost', color: '#e0f2fe' },
      { name: 'Lavender Mist', color: '#f3e8ff' },
      { name: 'Lilac Soft', color: '#ede9fe' },
      { name: 'Cotton White', color: '#fafafa' },
      { name: 'Sage Tint', color: '#f0fdf4' },
      { name: 'Ice Cyan', color: '#ecfeff' },
    ],
  },
];

export interface GradientPreset {
  id: string;
  name: string;
  value: string;
  colors: [string, string, ...string[]];
  type: 'linear' | 'radial';
  category?: 'heritage' | 'vibrant' | 'dark' | 'metallic';
}

export const GRADIENT_PRESETS: GradientPreset[] = [
  {
    id: 'grad-emerald',
    name: 'Imperial Emerald (شاہی زُمُرُد)',
    value: 'linear-gradient(135deg, #064e3b 0%, #047857 50%, #10b981 100%)',
    colors: ['#064e3b', '#047857', '#10b981'],
    type: 'linear',
    category: 'heritage',
  },
  {
    id: 'grad-saffron',
    name: 'Saffron Gold (زَعفران کۄنگ)',
    value: 'linear-gradient(135deg, #92400e 0%, #d97706 50%, #fde047 100%)',
    colors: ['#92400e', '#d97706', '#fde047'],
    type: 'linear',
    category: 'heritage',
  },
  {
    id: 'grad-chinar',
    name: 'Chinar Autumn Fire (بونہٕ نار)',
    value: 'linear-gradient(135deg, #7f1d1d 0%, #dc2626 50%, #f97316 100%)',
    colors: ['#7f1d1d', '#dc2626', '#f97316'],
    type: 'linear',
    category: 'heritage',
  },
  {
    id: 'grad-goldfoil',
    name: 'Kashmiri Gold Foil (طَلائی زَر)',
    value: 'linear-gradient(135deg, #78350f 0%, #d97706 35%, #fef08a 70%, #b45309 100%)',
    colors: ['#78350f', '#d97706', '#fef08a', '#b45309'],
    type: 'linear',
    category: 'metallic',
  },
  {
    id: 'grad-twilight',
    name: 'Dal Twilight (ڈَل شام)',
    value: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 45%, #6366f1 75%, #f43f5e 100%)',
    colors: ['#0f172a', '#1e1b4b', '#6366f1', '#f43f5e'],
    type: 'linear',
    category: 'heritage',
  },
  {
    id: 'grad-royal-purple',
    name: 'Mughal Royal Velvet (مُغلی مخمل)',
    value: 'linear-gradient(135deg, #2e1065 0%, #581c87 50%, #a855f7 100%)',
    colors: ['#2e1065', '#581c87', '#a855f7'],
    type: 'linear',
    category: 'vibrant',
  },
  {
    id: 'grad-rose',
    name: 'Gulab Blossom (کٲشُر گُلاب)',
    value: 'linear-gradient(135deg, #701a75 0%, #be185d 50%, #f472b6 100%)',
    colors: ['#701a75', '#be185d', '#f472b6'],
    type: 'linear',
    category: 'vibrant',
  },
  {
    id: 'grad-ocean',
    name: 'Glacier Stream (پیر پنچال آب)',
    value: 'linear-gradient(135deg, #082f49 0%, #0284c7 50%, #38bdf8 100%)',
    colors: ['#082f49', '#0284c7', '#38bdf8'],
    type: 'linear',
    category: 'vibrant',
  },
  {
    id: 'grad-khatamband',
    name: 'Mystic Khatamband (خَتَم بَنٛد)',
    value: 'linear-gradient(135deg, #042f2e 0%, #0f766e 50%, #2dd4bf 100%)',
    colors: ['#042f2e', '#0f766e', '#2dd4bf'],
    type: 'linear',
    category: 'heritage',
  },
  {
    id: 'grad-obsidian',
    name: 'Obsidian Silver Chrome (سیاہ چاندی)',
    value: 'linear-gradient(135deg, #09090b 0%, #27272a 50%, #71717a 100%)',
    colors: ['#09090b', '#27272a', '#71717a'],
    type: 'linear',
    category: 'metallic',
  },
  {
    id: 'grad-parchment',
    name: 'Antique Manuscript (قَدیم قلمی نسخہ)',
    value: 'linear-gradient(135deg, #fef3c7 0%, #fde68a 50%, #d97706 100%)',
    colors: ['#fef3c7', '#fde68a', '#d97706'],
    type: 'linear',
    category: 'heritage',
  },
  {
    id: 'grad-aurora',
    name: 'Northern Aurora (نورِ سَحر)',
    value: 'linear-gradient(135deg, #065f46 0%, #0284c7 50%, #eab308 100%)',
    colors: ['#065f46', '#0284c7', '#eab308'],
    type: 'linear',
    category: 'vibrant',
  },
  {
    id: 'grad-cyber',
    name: 'Cyber Neon (روشن نئون)',
    value: 'linear-gradient(135deg, #ec4899 0%, #8b5cf6 50%, #06b6d4 100%)',
    colors: ['#ec4899', '#8b5cf6', '#06b6d4'],
    type: 'linear',
    category: 'vibrant',
  },
  {
    id: 'grad-cosmic',
    name: 'Cosmic Indigo Night (شاہی شب)',
    value: 'linear-gradient(135deg, #020617 0%, #1e1b4b 60%, #4338ca 100%)',
    colors: ['#020617', '#1e1b4b', '#4338ca'],
    type: 'linear',
    category: 'dark',
  },
  {
    id: 'grad-radial-saffron',
    name: 'Radial Saffron Orb (دائرہٕ کۄنگ)',
    value: 'radial-gradient(circle, #fbbf24 0%, #d97706 60%, #78350f 100%)',
    colors: ['#fbbf24', '#d97706', '#78350f'],
    type: 'radial',
    category: 'heritage',
  },
  {
    id: 'grad-radial-emerald',
    name: 'Radial Emerald Jewel (دائرہٕ زُمُرُد)',
    value: 'radial-gradient(circle, #34d399 0%, #059669 60%, #064e3b 100%)',
    colors: ['#34d399', '#059669', '#064e3b'],
    type: 'radial',
    category: 'heritage',
  },
  {
    id: 'grad-radial-velvet',
    name: 'Radial Mughal Velvet (دائرہٕ مخمل)',
    value: 'radial-gradient(circle, #c084fc 0%, #7e22ce 60%, #3b0764 100%)',
    colors: ['#c084fc', '#7e22ce', '#3b0764'],
    type: 'radial',
    category: 'vibrant',
  },
];

// Aesthetic Kashmiri Background Themes & Palettes
export const KASHMIRI_PALETTES = [
  {
    id: 'saffron-dusk',
    name: 'Saffron Dusk (زَعفران / کۄنگ)',
    gradient: 'from-amber-600 via-orange-800 to-stone-950',
    color: '#d97706',
    textColor: '#ffffff',
  },
  {
    id: 'chinar-crimson',
    name: 'Chinar Crimson (بونہٕ رنگ)',
    gradient: 'from-red-800 via-rose-950 to-stone-950',
    color: '#991b1b',
    textColor: '#ffffff',
  },
  {
    id: 'dal-lake-emerald',
    name: 'Dal Lake Emerald (ڈَل سَر)',
    gradient: 'from-emerald-700 via-teal-900 to-stone-950',
    color: '#047857',
    textColor: '#ffffff',
  },
  {
    id: 'kashmiri-slate',
    name: 'Kashmiri Slate & Walnut (دوانکٔنٛد)',
    gradient: 'from-stone-800 via-stone-900 to-stone-950',
    color: '#292524',
    textColor: '#fafaf9',
  },
  {
    id: 'pir-panjal-snow',
    name: 'Pir Panjal Mist (پیر پَنچال)',
    gradient: 'from-slate-100 via-stone-200 to-amber-50',
    color: '#f5f5f4',
    textColor: '#1c1917',
  },
  {
    id: 'royal-pashmina',
    name: 'Royal Pashmina (پَشمِینہٕ)',
    gradient: 'from-amber-900 via-yellow-950 to-stone-950',
    color: '#78350f',
    textColor: '#fef3c7',
  },
  {
    id: 'islamic-teal',
    name: 'Khatamband Teal (خَتَم بَنٛد)',
    gradient: 'from-cyan-900 via-teal-950 to-stone-950',
    color: '#164e63',
    textColor: '#ffffff',
  },
];

export const QUICK_KASHMIRI_BAR = [
  { char: 'ٲ', name: 'ٲ' },
  { char: 'ٳ', name: 'ٳ' },
  { char: 'ۄ', name: 'ۄ' },
  { char: 'ۆ', name: 'ۆ' },
  { char: 'ؠ', name: 'ؠ' },
  { char: 'ٕ', name: 'ٕ' },
  { char: 'ژ', name: 'ژ' },
  { char: 'ٹ', name: 'ٹ' },
  { char: 'ڈ', name: 'ڈ' },
  { char: 'ڑ', name: 'ڑ' },
  { char: 'ں', name: 'ں' },
  { char: 'ھ', name: 'ھ' },
  { char: 'َ', name: 'َ' },
  { char: 'ِ', name: 'ِ' },
  { char: 'ُ', name: 'ُ' },
  { char: 'ْ', name: 'ْ' },
  { char: 'ّ', name: 'ّ' },
  { char: 'ٚ', name: 'ٚ' },
  { char: 'ٔ', name: 'ٔ' },
];

